/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanbDemoRouteImport } from './routes/planb-demo'
import { Route as IndexRouteImport } from './routes/index'

const PlanbDemoRoute = PlanbDemoRouteImport.update({
  id: '/planb-demo',
  path: '/planb-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/planb-demo': typeof PlanbDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/planb-demo': typeof PlanbDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/planb-demo': typeof PlanbDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/planb-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/planb-demo'
  id: '__root__' | '/' | '/planb-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanbDemoRoute: typeof PlanbDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planb-demo': {
      id: '/planb-demo'
      path: '/planb-demo'
      fullPath: '/planb-demo'
      preLoaderRoute: typeof PlanbDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanbDemoRoute: PlanbDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
